### ISSUE TITLE
Add an example app

### ISSUE THREAD

**Issue by tizmagik** [tizmagik/react-csjs#13]
An example app would help show sample `react-csjs` usage and also assist with local development

**Comment by code4cake** [comment]
Hey what do you mean by example app? like  a live preview app?

**Comment by tizmagik** [comment]
@dantesolis  Hm, I meant like what I've started to implement in #14 but what did you have in mind?

**Comment by code4cake** [comment]
Oh I don't know I was just looking for a good _1st time contributor_ issue for me to contribute on. 😄

**Comment by tizmagik** [comment]
A live preview app, maybe via gh-pages or something would be cool too! Happy to accept a PR for that, or if you have any other ideas feel free to submit an issue. I'll tack on the hacktoberfest label ;)

**Comment by tizmagik** [comment]
@dantesolis maybe #17 would be a good first time contributor issue for you? :)

**Comment by code4cake** [comment]
@tizmagik Then I'll work in issue  # 17 If no one is working on it. Thanks
