### ISSUE TITLE
Tagged decorator test

### ISSUE THREAD

**Issue by tizmagik** [tizmagik/react-csjs#17]
Add a test for the tagged decorator syntax introduced in #9

**Comment by code4cake** [comment]
I will work on this if it's ok 😄

**Comment by tizmagik** [comment]
Hey @dantesolis ! How is it going? Still planning to work on this? Do you need any help?

**Comment by code4cake** [comment]
@tizmagik hey yes sorry. Training for a certification exam now, but I would like to work on this. I'll get to it.

**Comment by tizmagik** [comment]
Now worries, take your time. Was just checking in to see if you needed any help. Good luck on the exam!

**Comment by code4cake** [comment]
@tizmagik thanks man sorry for the delayed response. I will work on it this weekend

**Comment by code4cake** [comment]
@tizmagik I have  stupid question, I'm having a bit of a problem with this.
1.  how do I run the app locally?
2.  the test is for the `src/index.js` file. Am I testing the `return DecoratedComponent ....`?

Sorry, this will be the first time I write a test and the first time I see a decorator being used. I would still love to have a go at it though.

**Comment by wKovacs64** [comment]
Hey @dantesolis. 
1. This project is just a higher order component (a component that wraps another component), so there's really nothing to run in the project itself. That said, you can play around with it locally by running the included [example app](../tree/master/example) which demonstrates its usage.
2. Check out the three syntax choices in the usage section of the [README](../tree/master/README.md#usage). We have tests for the 2nd ([decorator](https://github.com/tizmagik/react-csjs/blob/f4c23ee74a54c330b192681570c1270bed757974/test/index.test.js#L33)) and 3rd ([wrapped](https://github.com/tizmagik/react-csjs/blob/f4c23ee74a54c330b192681570c1270bed757974/test/index.test.js#L43)); you'd be testing the 1st (tagged decorator). The test would probably go in `index.test.js`, right above the decorator test. You'll probably want to add a `TaggedDecoratedButton` (or similar) export to `testUtil.js`, then import that and render it to the test DOM like we do in the other 2 cases.

~~Just to add some confusion... I screwed up the original tests so right now they're operating on strings of raw CSS when they should in fact be using CSJS'd (scoped) strings. Just submitted #31 to fix that.~~
Edit: fixed.

**Comment by wKovacs64** [comment]
How's it going, @dantesolis? Are you still looking to work on this?

**Comment by tizmagik** [comment]
I think @dantesolis might be AWOL on this :) @wKovacs64 feel free to add a test yourself if you have bandwidth. I've been bogged down with a deadline at work lately.
