### ISSUE TITLE
Requires babel-polyfill

### ISSUE THREAD

**Issue by SeeThruHead** [tizmagik/react-csjs#7]
react-csjs uses es6 Maps. Had some trouble tracking down my adding my code to a project, even though it's transpiled, was breaking in phantomjs. Might be nice to add this in the readme.

**Comment by tizmagik** [comment]
Ah, good call. We should probably be using `babel-plugin-transform-runtime`, or just use a normal object literal hash and remove this ES6 dependency entirely.

Happy to accept a PR with either of the above.

Thanks for reporting!
